name: fitness_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  flutter_bloc: ^8.0.1
  lottie: ^1.3.0
  flutter_svg: ^1.0.3
  equatable: ^2.0.3
  injectable: ^1.5.3
  form_field_validator: ^1.1.0
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dio: ^4.0.6
  freezed_annotation: ^2.0.1
  shared_preferences: ^2.0.13
  data_connection_checker: ^0.3.4
  dartz: ^0.10.1
  json_annotation: ^4.4.0
  flutter_styled_toast:
    git:
      url: https://github.com/nirajbpant/flutter_styled_toast
      ref: null-safety
  google_sign_in: ^5.3.0
  syncfusion_flutter_charts: ^20.1.52
  qr_code_scanner: ^0.7.0
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  http: ^0.13.4


dev_dependencies:
  lint: ^1.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  mockito: ^5.1.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
  assets:
    - assets/logo/
    - assets/icons/
    - assets/env/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset : assets/fonts/Lato-BlackItalic.ttf
        - asset : assets/fonts/Lato-Bold.ttf
        - asset : assets/fonts/Lato-BoldItalic.ttf
        - asset : assets/fonts/Lato-Italic.ttf
        - asset : assets/fonts/Lato-Light.ttf
        - asset : assets/fonts/Lato-LightItalic.ttf
        - asset : assets/fonts/Lato-Regular.ttf
        - asset : assets/fonts/Lato-Thin.ttf
        - asset : assets/fonts/Lato-ThinItalic.ttf

 



